export default {
  photo: "profile.png",
  name: "Aleksandr Ulyanov",
  position: "Frontend Developer",
  site: "https://github.com/sashauly",
  email: "sashauly.code@gmail.com",
  resume: "https://hh.ru/resume/f125f0d0ff0bd8222b0039ed1f6c354b38686e",
  about: "I am a frontend developer as you can see. Trying my best so far...",
  interests: "Maybe some day this section will go absolete",
  twitter: "",
  facebook: "",
  instagram: "",
  github: "https://github.com/sashauly",
  telegram: "https://t.me/sashauly",
};
